"""
backend/playbooks/recommend.py

Runs graph retrieval against the user's profile, then streams a SHORT
intro line and attaches structured product cards — top 3 highlighted
with deterministic "why this matches" keyword tags (see
backend/match_keywords.py), remaining shown plainly.

Also retrieves matching combo deals and collaborative-filter picks from
the user preference graph, which are prepended to the response so the
widget can show them before the individual top picks.

Per-product reasoning used to be LLM-written prose (1-2 sentences each),
which produced long, repetitive chat bubbles on live testing. That's
been replaced by graph-derived keyword tags rendered directly on each
card — faster, can't hallucinate, and far more scannable. The LLM's only
remaining job here is one short opening line.

Keyword inputs (matched concerns, texture, ingredients, free_from) come
straight off result.top_picks — retrieval.py's query already collects
them for every product in every fallback round, so no second graph
round-trip is needed here.

Also records R (recommended) events in the history store for
every product in top_picks.
"""

import json
import os
from typing import AsyncGenerator

from falkordb import FalkorDB

from backend.playbooks.base import build_system_prompt, load_prompt, stream_response, emit_ui_data
from backend.profile import (
    compact_profile_for_prompt,
    load_profile,
    parse_profile,
    record_event,
)
from backend.retrieval import retrieve, PRICE_TIER_TO_MAX
from backend.match_keywords import build_keywords, build_explanation_chips
from backend.combo_retrieval import retrieve_combos
from backend.user_graph import sync_user_profile, record_user_choice, get_collaborative_picks
from backend.explain_api import build_explain_payload

# ---------------------------------------------------------------------------
# Promotions lookup  (generated by scripts/scrape_promotions.py)
# ---------------------------------------------------------------------------

_PROMOS: dict[str, str] = {}


def _load_promos() -> dict[str, str]:
    global _PROMOS
    if _PROMOS:
        return _PROMOS
    path = os.path.join(
        os.path.dirname(__file__), "..", "..", "data", "promotions.json"
    )
    path = os.path.normpath(path)
    try:
        with open(path, "r", encoding="utf-8") as f:
            raw = json.load(f)
        _PROMOS = {k: v for k, v in raw.items() if v}
    except Exception:
        _PROMOS = {}
    return _PROMOS


# ---------------------------------------------------------------------------
# Allergen transparency note
# ---------------------------------------------------------------------------

# Maps profile allergen keys → the names those allergens appear under in the
# graph's AllergenClass nodes (used for case-insensitive matching).
_ALLERGEN_DISPLAY: dict[str, str] = {
    "fragrance": "Fragrance",
    "alcohol":   "Alcohol",
    "sulfate":   "Sulfates",
    "paraben":   "Parabens",
    "silicone":  "Silicone",
}


def _allergen_note(requested: list[str], top_picks: list[dict]) -> str:
    """Build a one-line transparency note about which allergens were verified.

    Compares the user's requested allergen-free list against the `free_from`
    field on the returned top picks (which holds the graph's AllergenClass
    node names). Returns empty string when no allergen preference was set.
    """
    real = [a for a in requested if a and a != "none"]
    if not real:
        return ""

    # Collect all confirmed free-from names across top picks (lower-cased)
    confirmed_names: set[str] = set()
    for p in top_picks:
        for name in (p.get("free_from") or []):
            confirmed_names.add(name.lower())

    confirmed, unverified = [], []
    for allergen in real:
        label = _ALLERGEN_DISPLAY.get(allergen, allergen.capitalize())
        # Match if the allergen key appears anywhere in a free_from name or vice versa
        is_confirmed = any(
            allergen in name or name in allergen
            for name in confirmed_names
        )
        (confirmed if is_confirmed else unverified).append(label)

    parts = []
    if confirmed:
        parts.append("✓ Free from: " + " · ".join(confirmed))
    if unverified:
        parts.append(
            "⚠ Couldn't verify: " + " · ".join(unverified)
            + " — check the ingredient list to be sure"
        )
    return "  |  ".join(parts)


# ---------------------------------------------------------------------------
# FalkorDB connection
# ---------------------------------------------------------------------------

def _get_graph():
    db = FalkorDB(
        host=os.getenv("FALKORDB_HOST", "localhost"),
        port=int(os.getenv("FALKORDB_PORT", 6379)),
    )
    return db.select_graph(os.getenv("FALKORDB_GRAPH", "dotandkey"))


# ---------------------------------------------------------------------------
# Profile → retrieval profile dict
# ---------------------------------------------------------------------------

def _build_retrieval_profile(profile_id: str) -> dict:
    raw = load_profile(profile_id)
    parsed = parse_profile(raw)
    price_tier = parsed.get("price_tier", "")
    max_price = PRICE_TIER_TO_MAX.get(price_tier)  # None when tier is "any" or unset
    return {
        "category":      parsed.get("category", ""),
        "skin_types":    parsed.get("skin_types", []),
        "concerns":      parsed.get("concerns", []),
        "season":        parsed.get("season", ""),
        "texture":       parsed.get("texture", ""),
        # "none" is a UI sentinel meaning "no preference" — strip before retrieval
        # so it doesn't try to match a non-existent "none" AllergenClass node.
        "allergen_free": [a for a in parsed.get("allergen_free", []) if a != "none"],
        "max_price":     max_price,
        "price_tier":    price_tier,
        "size_pref":     parsed.get("size_pref", ""),
    }


# ---------------------------------------------------------------------------
# Serialisers — two different audiences need two different shapes
# ---------------------------------------------------------------------------

def _compact_product(p: dict) -> dict:
    """Trimmed product dict for the LLM PROMPT — just enough for it to
    write one short, profile-aware opening line. No per-product detail
    needed anymore since reasoning moved to keyword tags."""
    return {"title": p["title"]}


def _card_product(p: dict, with_keywords: bool = False,
                   parsed_profile: dict | None = None,
                   explanation: dict | None = None) -> dict:
    """Trimmed product dict for the WIDGET.

    - keywords (3 chips): concern / texture / ingredient / free-from tags
    - explanation_chips (5 chips): capability scores + tradeoffs, top-picks only
    - explanation: full structured ranking evidence dict, top-picks only
    """
    promos = _load_promos()
    user_concerns = (parsed_profile or {}).get("concerns") or []
    card = {
        "sku":              p["sku"],
        "title":            p["title"],
        "price":            p["price"],
        "compare_at_price": p.get("compare_at_price") or 0,
        "category":         p.get("category_raw", ""),
        "url":              p.get("url", ""),
        "image_url":        p.get("image_url", ""),
        "promo_label":      promos.get(p["sku"]),
        "variant":          p.get("variant", ""),
    }
    if with_keywords:
        card["keywords"] = build_keywords(
            matched_concerns=p.get("matched_concerns", []),
            texture=p.get("texture", ""),
            key_ingredients=p.get("ingredients", []),
            free_from=p.get("free_from", []),
            all_skin_types=p.get("all_skin_types", []),
        )
        card["explanation_chips"] = build_explanation_chips(p, user_concerns)
    if explanation is not None:
        card["explanation"] = explanation
    return card


def _card_combo(c: dict) -> dict:
    """Trim a combo dict to the fields the widget needs to render a combo card."""
    return {
        "sku":              c["sku"],
        "title":            c["title"],
        "price":            c["price"],
        "compare_at_price": c.get("compare_at_price") or 0,
        "url":              c.get("url", ""),
        "image_url":        c.get("image_url", ""),
        "matched_skin_types": c.get("matched_skin_types", []),
        "matched_concerns":   c.get("matched_concerns", []),
        "components":       c.get("components", []),
    }


# ---------------------------------------------------------------------------
# Main playbook entry point
# ---------------------------------------------------------------------------

async def run(
    profile_id: str,
    user_message: str,
    router_args: dict,
) -> AsyncGenerator[str, None]:
    """Run retrieval, then stream a short recommendation intro.

    Response payload order (all via emit_ui_data, rendered top-to-bottom):
      1. combos  — matching bundle deals (shown ABOVE individual picks)
      2. top_picks + remaining — individual product cards
      3. collab_picks — SKUs chosen by similar users (optional, non-empty only)
    """

    retrieval_profile = _build_retrieval_profile(profile_id)
    raw_profile = load_profile(profile_id)
    parsed_profile = parse_profile(raw_profile)

    # Guard: if category is still missing, we can't retrieve
    if not retrieval_profile.get("category"):
        yield "What kind of product are you looking for — sunscreen, moisturizer, or something else?"
        return

    graph = _get_graph()

    # ── 1. Combo retrieval (runs before individual products) ─────────────────
    combos = retrieve_combos(graph, parsed_profile)

    # ── 2. Individual product retrieval ──────────────────────────────────────
    import logging as _logging
    _rlog = _logging.getLogger(__name__)
    _rlog.debug(
        "BUDGET_SESSION | profile_id=%s | price_tier=%s | allergen=%s | category=%s",
        profile_id,
        retrieval_profile.get("price_tier") or "none",
        retrieval_profile.get("allergen_free") or [],
        retrieval_profile.get("category"),
    )

    # Tier 3: LLM vague-intent interpretation — only when Tier 1+2 extract nothing.
    # Adds ~1–2 s for vague queries only; precise ingredient queries skip this path.
    from backend.query_intent import extract_query_tokens as _etq
    from backend.vague_intent import interpret_vague_query as _ivq
    _quick_tokens = _etq(user_message)
    _vague_tokens: list[str] = []
    if not _quick_tokens:
        _vague_tokens = await _ivq(user_message)
        if _vague_tokens:
            _rlog.debug("TIER3_VAGUE | tokens=%s", _vague_tokens)

    from backend.sensitivity_memory import sensitivity_from_profile
    from backend.behavioral_learning import get_behavioral_prefs
    _sensitivity       = sensitivity_from_profile(parsed_profile)
    _behavioral_prefs  = get_behavioral_prefs(profile_id)

    result = retrieve(graph, retrieval_profile, user_message=user_message,
                      vague_tokens=_vague_tokens, sensitivity=_sensitivity,
                      behavioral_prefs=_behavioral_prefs)

    _rlog.debug(
        "BUDGET_SESSION | products_before_dedup=n/a | top_picks=%d | remaining=%d"
        " | dropped=%s | expanded_tier=%r",
        len(result.top_picks), len(result.remaining),
        result.dropped_filters, result.expanded_budget_tier,
    )

    if result.total == 0:
        yield ("Couldn't find a match for that combination — "
               "want to try loosening the filters a bit?")
        yield emit_ui_data({"combos": combos, "top_picks": [], "remaining": []})
        return

    # ── 3. Collaborative filtering picks ─────────────────────────────────────
    collab_skus = get_collaborative_picks(
        profile_id,
        category=retrieval_profile["category"],
        limit=4,
    )
    # Filter collab SKUs to ones actually in our result set (product graph is
    # the source of truth; user graph may reference discontinued SKUs)
    all_result_skus = {p["sku"] for p in result.top_picks + result.remaining}
    collab_cards = [
        _card_product(p)
        for p in (result.top_picks + result.remaining)
        if p["sku"] in collab_skus and p["sku"] in all_result_skus
    ]

    # ── 4. LLM intro line ────────────────────────────────────────────────────
    top_json    = json.dumps([_compact_product(p) for p in result.top_picks], indent=2)
    dropped_str = (", ".join(result.dropped_filters)
                   if result.dropped_filters else "none")

    recommend_prompt = load_prompt("recommend.md")
    extra = (
        recommend_prompt
        .replace("{profile_line}", compact_profile_for_prompt(profile_id))
        .replace("{top_picks_json}", top_json)
        .replace("{remaining_count}", str(len(result.remaining)))
        .replace("{dropped_filters}", dropped_str)
    )

    system = build_system_prompt(profile_id, extra_context=extra)

    async for token in stream_response(system, profile_id, user_message):
        yield token

    # ── 5. Profile summary chips ──────────────────────────────────────────────
    # Compact "Dry Skin • Fragrance-free • Under ₹300" row shown above cards.
    # No retrieval terminology, no tier names for expansions, no allergen audit.
    _TIER_DISPLAY = {
        "under_300": "Under ₹300", "under_600": "Under ₹600",
        "under_1000": "Under ₹1,000",
        # "any" = no budget limit → omit from summary (nothing useful to say)
    }
    _ALLERGEN_DISPLAY_COMPACT = {
        "fragrance": "Fragrance-free", "alcohol": "Alcohol-free",
        "sulfate":   "Sulfate-free",   "paraben": "Paraben-free",
        "silicone":  "Silicone-free",
    }
    summary_chips: list[str] = []

    # skin type(s)
    skin_types = parsed_profile.get("skin_types") or []
    if isinstance(skin_types, str):
        skin_types = [s for s in skin_types.split(",") if s]
    if skin_types:
        summary_chips.append(
            " & ".join(s.capitalize() + " skin" for s in skin_types[:2])
        )

    # allergens (skip "none" sentinel)
    allergens = parsed_profile.get("allergen_free") or []
    if isinstance(allergens, str):
        allergens = [a for a in allergens.split(",") if a]
    for a in allergens:
        label = _ALLERGEN_DISPLAY_COMPACT.get(a)
        if label:
            summary_chips.append(label)

    # budget (only show if a real tier was set; omit "any")
    requested_tier = retrieval_profile.get("price_tier") or ""
    budget_label   = _TIER_DISPLAY.get(requested_tier, "")
    if budget_label:
        summary_chips.append(budget_label)

    # ── 6. Structured UI payload ──────────────────────────────────────────────
    # Build per-product explanations for top picks using the new API
    explanations: list[dict] = []
    
    # We need a graph connection for build_explain_payload
    from falkordb import FalkorDB
    import os
    db = FalkorDB(
        host=os.getenv("FALKORDB_HOST", "localhost"),
        port=int(os.getenv("FALKORDB_PORT", 6379)),
    )
    graph = db.select_graph(os.getenv("FALKORDB_GRAPH", "dotandkey"))
    
    for rank, p in enumerate(result.top_picks, start=1):
        try:
            exp = build_explain_payload(p["sku"], profile_id, graph)
            if "error" not in exp:
                exp["rank_in_recommendation"] = rank
        except Exception:
            exp = {}
        explanations.append(exp)

    payload: dict = {
        "combos":        [_card_combo(c) for c in combos],
        "top_picks":     [
            _card_product(p, with_keywords=True,
                          parsed_profile=parsed_profile,
                          explanation=explanations[i] if i < len(explanations) else None)
            for i, p in enumerate(result.top_picks)
        ],
        "remaining":     [_card_product(p) for p in result.remaining],
        "collab_picks":  collab_cards,
        "profile_chips": summary_chips,
    }
    # Budget expansion: one friendly sentence, no warning icon, no tier names
    if result.expanded_budget_tier:
        payload["budget_expansion_message"] = (
            "Couldn't find an exact match for your budget, "
            "so I found the closest options."
        )
    yield emit_ui_data(payload)

    # ── 6. Post-stream: sync user graph + record events ───────────────────────
    category = raw_profile.get("category", "")
    try:
        sync_user_profile(profile_id, parsed_profile)
        for p in result.top_picks:
            record_user_choice(profile_id, p["sku"], event="R", price=p["price"] or 0)
            record_event(
                profile_id=profile_id,
                sku=p["sku"],
                category=category,
                event="R",
                price=p["price"] or 0,
            )
    except Exception:
        pass   # user graph is non-critical — never let it break the response